import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  Grid,
  Card,
  CardContent,
  Button,
  Stack,
  Chip,
  Paper,
  Tabs,
  Tab,
} from '@mui/material';
import SearchIcon from '@mui/icons-material/Search';
import ShareIcon from '@mui/icons-material/Share';
import EmailIcon from '@mui/icons-material/Email';
import AutoGraphIcon from '@mui/icons-material/AutoGraph';
import CampaignIcon from '@mui/icons-material/Campaign';
import CodeIcon from '@mui/icons-material/Code';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircle';
import TouchAppIcon from '@mui/icons-material/TouchApp';
import { Link } from 'react-router-dom';

const services = [
  {
    icon: <SearchIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Search Engine Optimization (SEO)',
    desc: 'Improve search rankings, drive high-intent organic traffic, and optimize technical site health.',
    highlights: ['Keyword Strategy', 'Technical Audits', 'On-Page & Off-Page SEO'],
  },
  {
    icon: <ShareIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Social Media Growth',
    desc: 'Build engaged communities across Meta, LinkedIn, and Instagram with high-impact content.',
    highlights: ['Content Scheduling', 'Audience Insights', 'Brand Awareness'],
  },
  {
    icon: <AutoGraphIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Pay-Per-Click Advertising (PPC)',
    desc: 'Maximize customer acquisition ROI through precision-targeted Google Ads & Meta campaigns.',
    highlights: ['Ad Copywriting', 'Conversion Tracking', 'A/B Testing'],
  },
  {
    icon: <EmailIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Email Marketing & Automation',
    desc: 'Nurture leads and drive repeat sales with automated drip campaigns and targeted newsletters.',
    highlights: ['List Segmentation', 'Automated Flows', 'Retention Strategy'],
  },
  {
    icon: <CampaignIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Content Marketing',
    desc: 'Establish industry authority with blog posts, strategic landing pages, and educational guides.',
    highlights: ['Editorial Planning', 'Lead Magnets', 'Brand Storytelling'],
  },
  {
    icon: <CodeIcon fontSize="large" sx={{ color: '#0F52BA' }} />,
    title: 'Conversion Rate Optimization (CRO)',
    desc: 'Turn your website visitors into paying customers by optimizing landing page UX and copy.',
    highlights: ['Heatmap Analysis', 'Funnel Optimization', 'UX Auditing'],
  },
];

const strategies = [
  {
    title: 'Organic Search Strategy',
    description: 'Long-term compounding traffic generated by optimizing high-volume search queries relevant to your industry.',
    metrics: '3x-5x ROI over 6-12 months',
  },
  {
    title: 'Paid Media Campaigns',
    description: 'Immediate lead generation and scalable customer acquisition using hyper-targeted paid advertising.',
    metrics: 'Instant visibility & instant analytics',
  },
  {
    title: 'Retention & Email Automation',
    description: 'Maximize Customer Lifetime Value (LTV) through targeted lifecycle sequences and continuous re-engagement.',
    metrics: 'Up to 40% higher repeat purchases',
  },
];

const workflowSteps = [
  { step: '01', title: 'Audit & Analysis', desc: 'Deep-dive evaluation of current online presence and competitor benchmarking.' },
  { step: '02', title: 'Strategy Blueprint', desc: 'Designing custom campaigns targeting your ideal customer demographics.' },
  { step: '03', title: 'Execution & Launch', desc: 'Deploying high-converting creatives, landing pages, and search ads.' },
  { step: '04', title: 'Optimize & Scale', desc: 'Continuous data monitoring and budget reallocation to high-performing channels.' },
];

const DigitalMarketing = () => {
  const [activeTab, setActiveTab] = useState(0);

  const handleTabChange = (event, newValue) => {
    setActiveTab(newValue);
  };

  return (
    <Box sx={{ bgcolor: '#F8FAFC', minHeight: '100vh', pb: { xs: 6, md: 10 } }}>
      {/* Hero Section */}
      <Box
        sx={{
          bgcolor: 'background.paper',
          py: { xs: 6, sm: 8, md: 12 },
          px: { xs: 2, sm: 3 },
          borderBottom: '1px solid #E2E8F0',
          background: 'radial-gradient(circle at 10% 20%, rgba(15, 82, 186, 0.05) 0%, transparent 60%)',
        }}
      >
        <Container maxWidth="lg" disableGutters>
          <Box sx={{ maxWidth: 800, mx: 'auto', textAlign: 'center' }}>
            <Chip
              icon={<TouchAppIcon sx={{ fontSize: '16px !important' }} />}
              label="Comprehensive Digital Strategy"
              color="primary"
              variant="outlined"
              size="small"
              sx={{ mb: 2.5, fontWeight: 700, borderRadius: '20px', bgcolor: 'rgba(15, 82, 186, 0.04)' }}
            />
            <Typography
              variant="h2"
              component="h1"
              sx={{
                fontSize: { xs: '2rem', sm: '2.75rem', md: '3.5rem' },
                fontWeight: 800,
                letterSpacing: '-1px',
                color: '#0F172A',
                mb: 2,
                lineHeight: 1.2,
              }}
            >
              Master Every Pillar of{' '}
              <Box
                component="span"
                sx={{
                  background: 'linear-gradient(135deg, #0F52BA 0%, #2E7D32 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                }}
              >
                Digital Marketing
              </Box>
            </Typography>
            <Typography
              variant="h6"
              color="text.secondary"
              sx={{
                fontWeight: 400,
                fontSize: { xs: '0.975rem', sm: '1.1rem', md: '1.15rem' },
                lineHeight: 1.6,
                mb: 4,
                px: { xs: 1, sm: 0 },
              }}
            >
              Explore actionable channels, proven frameworks, and growth playbooks tailored to attract, convert, and retain your audience.
            </Typography>
            <Stack
              direction={{ xs: 'column', sm: 'row' }}
              spacing={2}
              justifyContent="center"
              sx={{ width: '100%' }}
            >
              <Button
                fullWidth
                variant="contained"
                size="large"
                component={Link}
                to="/register"
                endIcon={<ArrowForwardIcon />}
                sx={{
                  py: 1.6,
                  px: 4,
                  fontWeight: 700,
                  borderRadius: 2.5,
                  maxWidth: { sm: 'auto' },
                  boxShadow: '0 10px 25px -5px rgba(15, 82, 186, 0.4)',
                }}
              >
                Start Growing Free
              </Button>
              <Button
                fullWidth
                variant="outlined"
                size="large"
                component={Link}
                to="/tools"
                sx={{
                  py: 1.6,
                  px: 4,
                  fontWeight: 600,
                  borderRadius: 2.5,
                  maxWidth: { sm: 'auto' },
                  borderColor: '#CBD5E1',
                  color: '#334155',
                }}
              >
                Explore Marketing Tools
              </Button>
            </Stack>
          </Box>
        </Container>
      </Box>

      {/* Core Pillars Grid */}
      <Container maxWidth="lg" sx={{ mt: { xs: 6, md: 10 }, px: { xs: 2, sm: 3 } }}>
        <Box sx={{ textAlign: 'center', mb: { xs: 4, md: 7 }, maxWidth: 650, mx: 'auto' }}>
          <Typography
            variant="h4"
            sx={{
              fontWeight: 800,
              color: '#0F172A',
              mb: 1.5,
              fontSize: { xs: '1.5rem', sm: '2rem', md: '2.25rem' },
            }}
          >
            The 6 Key Pillars of Online Growth
          </Typography>
          <Typography color="text.secondary" sx={{ fontSize: { xs: '0.9rem', sm: '1.05rem' } }}>
            Combine organic and paid marketing strategies to create scalable revenue engines.
          </Typography>
        </Box>

        <Grid container spacing={{ xs: 2.5, md: 3.5 }}>
          {services.map((service, idx) => (
            <Grid key={idx} size={{ xs: 12, sm: 6, md: 4 }}>
              <Card
                elevation={0}
                sx={{
                  height: '100%',
                  display: 'flex',
                  flexDirection: 'column',
                  borderRadius: 4,
                  border: '1px solid #E2E8F0',
                  transition: 'all 0.3s ease',
                  '&:hover': {
                    transform: { md: 'translateY(-6px)' },
                    borderColor: '#0F52BA',
                    boxShadow: '0px 16px 30px rgba(15, 82, 186, 0.08)',
                  },
                }}
              >
                <CardContent sx={{ p: { xs: 2.5, sm: 3, md: 4 }, flexGrow: 1 }}>
                  <Box
                    sx={{
                      width: 48,
                      height: 48,
                      borderRadius: 3,
                      bgcolor: 'rgba(15, 82, 186, 0.08)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      mb: 2.5,
                    }}
                  >
                    {service.icon}
                  </Box>
                  <Typography variant="h6" sx={{ fontWeight: 700, color: '#0F172A', mb: 1.5, fontSize: '1.1rem' }}>
                    {service.title}
                  </Typography>
                  <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6, mb: 3 }}>
                    {service.desc}
                  </Typography>
                  <Stack spacing={1}>
                    {service.highlights.map((item, itemIdx) => (
                      <Box key={itemIdx} sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <CheckCircleOutlineIcon sx={{ color: '#2E7D32', fontSize: 18, flexShrink: 0 }} />
                        <Typography variant="caption" sx={{ fontWeight: 600, color: '#475569' }}>
                          {item}
                        </Typography>
                      </Box>
                    ))}
                  </Stack>
                </CardContent>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Container>

      {/* Interactive Framework Section */}
      <Box
        sx={{
          bgcolor: 'background.paper',
          py: { xs: 6, md: 10 },
          mt: { xs: 6, md: 10 },
          borderTop: '1px solid #E2E8F0',
          borderBottom: '1px solid #E2E8F0',
          px: { xs: 2, sm: 3 },
        }}
      >
        <Container maxWidth="lg" disableGutters>
          <Box sx={{ textAlign: 'center', mb: { xs: 4, md: 6 } }}>
            <Typography
              variant="h4"
              sx={{
                fontWeight: 800,
                color: '#0F172A',
                mb: 1.5,
                fontSize: { xs: '1.5rem', sm: '2rem', md: '2.25rem' },
              }}
            >
              Which Marketing Engine Fits Your Business?
            </Typography>
            <Typography color="text.secondary" sx={{ fontSize: { xs: '0.9rem', sm: '1rem' } }}>
              Compare strategic approaches based on speed, long-term impact, and resource requirements.
            </Typography>
          </Box>

          <Paper
            elevation={0}
            sx={{
              border: '1px solid #E2E8F0',
              borderRadius: 4,
              p: { xs: 2, sm: 3, md: 4 },
              overflow: 'hidden',
            }}
          >
            <Tabs
              value={activeTab}
              onChange={handleTabChange}
              variant="scrollable"
              scrollButtons="auto"
              allowScrollButtonsMobile
              indicatorColor="primary"
              textColor="primary"
              sx={{ mb: 3, borderBottom: '1px solid #E2E8F0' }}
            >
              <Tab label="Organic SEO" sx={{ fontWeight: 700, fontSize: { xs: '0.875rem', sm: '1rem' } }} />
              <Tab label="Paid Media" sx={{ fontWeight: 700, fontSize: { xs: '0.875rem', sm: '1rem' } }} />
              <Tab label="Email & Retention" sx={{ fontWeight: 700, fontSize: { xs: '0.875rem', sm: '1rem' } }} />
            </Tabs>

            <Box sx={{ pt: 1 }}>
              <Grid container spacing={{ xs: 3, md: 4 }} alignItems="center">
                <Grid size={{ xs: 12, md: 7 }}>
                  <Typography
                    variant="h5"
                    sx={{ fontWeight: 700, color: '#0F172A', mb: 1.5, fontSize: { xs: '1.25rem', md: '1.5rem' } }}
                  >
                    {strategies[activeTab].title}
                  </Typography>
                  <Typography
                    variant="body1"
                    color="text.secondary"
                    sx={{ lineHeight: 1.7, mb: 3, fontSize: { xs: '0.925rem', sm: '1rem' } }}
                  >
                    {strategies[activeTab].description}
                  </Typography>
                  <Chip
                    label={`Expected Result: ${strategies[activeTab].metrics}`}
                    color="success"
                    variant="outlined"
                    sx={{
                      fontWeight: 700,
                      borderRadius: 2,
                      height: 'auto',
                      py: 0.75,
                      '& .MuiChip-label': { whiteSpace: 'normal' },
                    }}
                  />
                </Grid>
                <Grid size={{ xs: 12, md: 5 }}>
                  <Card
                    elevation={0}
                    sx={{
                      p: { xs: 2.5, sm: 3.5 },
                      bgcolor: '#F8FAFC',
                      border: '1px dashed #CBD5E1',
                      borderRadius: 3,
                      textAlign: 'center',
                    }}
                  >
                    <Typography variant="subtitle2" color="text.secondary" gutterBottom sx={{ letterSpacing: 1 }}>
                      RECOMMENDED FOCUS
                    </Typography>
                    <Typography variant="h6" sx={{ fontWeight: 800, color: '#0F52BA', fontSize: '1.05rem' }}>
                      {activeTab === 0 && 'High Quality Content & Technical Audits'}
                      {activeTab === 1 && 'Targeted Meta Ads & Google Search Ads'}
                      {activeTab === 2 && 'Segmented Lead Flows & Newsletters'}
                    </Typography>
                  </Card>
                </Grid>
              </Grid>
            </Box>
          </Paper>
        </Container>
      </Box>

      {/* 4-Step Process Section */}
      <Container maxWidth="lg" sx={{ mt: { xs: 6, md: 10 }, px: { xs: 2, sm: 3 } }}>
        <Box sx={{ textAlign: 'center', mb: { xs: 4, md: 7 } }}>
          <Typography
            variant="h4"
            sx={{
              fontWeight: 800,
              color: '#0F172A',
              mb: 1.5,
              fontSize: { xs: '1.5rem', sm: '2rem', md: '2.25rem' },
            }}
          >
            Our 4-Step Marketing Workflow
          </Typography>
          <Typography color="text.secondary" sx={{ fontSize: { xs: '0.9rem', sm: '1rem' } }}>
            A battle-tested framework for consistent and repeatable growth.
          </Typography>
        </Box>

        <Grid container spacing={2.5}>
          {workflowSteps.map((item, idx) => (
            <Grid key={idx} size={{ xs: 12, sm: 6, md: 3 }}>
              <Paper
                elevation={0}
                sx={{
                  p: { xs: 2.5, sm: 3, md: 3.5 },
                  height: '100%',
                  borderRadius: 4,
                  border: '1px solid #E2E8F0',
                  bgcolor: '#FFFFFF',
                }}
              >
                <Typography variant="h3" sx={{ fontWeight: 900, color: 'rgba(15, 82, 186, 0.15)', mb: 1 }}>
                  {item.step}
                </Typography>
                <Typography variant="h6" sx={{ fontWeight: 700, color: '#0F172A', mb: 1, fontSize: '1.1rem' }}>
                  {item.title}
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>
                  {item.desc}
                </Typography>
              </Paper>
            </Grid>
          ))}
        </Grid>
      </Container>
    </Box>
  );
};

export default DigitalMarketing;